Models/ErrorViewModel.cs
namespace RomenITELEC1C.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Instructor.cs
namespace RomenITELEC1C.Models
{
    public enum Rank
    {
        Instructor, AssistProf, Prof
    }
    public class Instructor
    {
        public int InstructorId { get; set; }

        public string InstructorFirstName { get; set; }

        public string InstructorLastName { get; set; }

        public bool IsTenured { get; set; }

        public DateTime DateHired { get; set; }

        public Rank Rank { get; set; }

        public string InstructorEmail { get; set; }

    }
}

Models/StudentModel.cs
namespace RomenITELEC1C.Models
{
    public enum Course
    {
        BSCS, BSIT,BSIS
    }
    public class StudentModel
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public DateTime DateEnrolled { get; set; }
        public Course StudentCourse { get; set; }
        public string Email { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RomenITELEC1C.Models;
using System.Diagnostics;

namespace RomenITELEC1C.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using RomenITELEC1C.Models;

namespace RomenITELEC1C.Controllers
{
    public class InstructorController : Controller
    {
        List<Instructor> InstructorList = new List<Instructor>()
        {
            new Instructor()
            {
                InstructorId=1, InstructorFirstName = "Gabriel", InstructorLastName = "Montano", IsTenured= true,
                InstructorEmail ="gabrielmontano@ust.edu.ph", Rank = Rank.Instructor, DateHired = DateTime.Now
            },
            new Instructor()
            {
                InstructorId=2, InstructorFirstName = "Goldie", InstructorLastName = "Pare", IsTenured= true,
                InstructorEmail ="goldiemay@ust.edu.ph", Rank = Rank.AssistProf, DateHired = DateTime.Parse("28/09/2022")            },
            new Instructor()
            {
                InstructorId=3, InstructorFirstName = "Ashley", InstructorLastName = "Santos", IsTenured= true,
                InstructorEmail ="alyssamarie@ust.edu.ph", Rank = Rank.Prof, DateHired = DateTime.Parse("28/07/2022")
            }
        };
        public IActionResult Index()
        {

            return View(InstructorList);
        }

        public IActionResult ShowDetail(int id)
        {
            //Search for the student whose id matches the given id
            Instructor? instructor = InstructorList.FirstOrDefault(st => st.InstructorId == id);

            if (instructor != null)//was an instructor found?
                return View(instructor);

            return NotFound();
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using RomenITELEC1C.Models;

namespace RomenITELEC1C.Controllers;

public class StudentController : Controller
{
    public IActionResult Index()
    {
        StudentModel st = new StudentModel();
        st.StudentId = 2021160625;
        st.StudentName = "Alyssa Marie R. Romen";
        st.DateEnrolled = DateTime.Parse("29/07/2023");
        st.StudentCourse = Course.BSIT;
        st.Email = "alyssamarie.romen.cics@ust.edu.ph";

        ViewBag.StudentModel = st;
        return View();
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>
 

Views/Instructor/Index.cshtml
@{
}
@model IEnumerable<RomenITELEC1C.Models.Instructor>

<h1>Instructor View</h1>

<table class="table table-dark">
    <tr>
        <th>ID:</th>
        <th>Name: </th>
        <th>IsTenured: </th>
        <th>Email: </th>
        <th>Rank: </th>
        <th>Date Hired: </th>
        <th>Details:</th>
    </tr>

    @foreach(var Instructor in Model)
    {
        <tr>
            <td>@Instructor.InstructorId</td>
            <td>@Instructor.InstructorFirstName @Instructor.InstructorLastName</td>
            <td>@Instructor.IsTenured</td>
            <td>@Instructor.InstructorEmail</td>
            <td>@Instructor.Rank</td>
            <td>@Instructor.DateHired</td>
            <td><a asp-action="ShowDetail" asp-route-id="@Instructor.InstructorId">Show Details</a></td>
        </tr>
        
    }
</table>

Views/Instructor/ShowDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Instructor;

<h1>Instructor Details</h1>

<table class="table table-dark">
    <tr>
        <th>Id</th>
        <td>@Model.InstructorId</td>
    </tr>
    <tr>
        <th>Last Name</th>
        <td>@Model.InstructorLastName</td>
    </tr>
    <tr>
        <th>First Name</th>
        <td>@Model.InstructorFirstName</td>
    </tr>
    <tr>
        <th>Rank</th>
        <td>@Model.Rank</td>
    </tr>
    <tr>
        <th>Hiring Date</th>
        <td>@Model.DateHired</td>
    </tr>
    <tr>
        <th>Is Tenured</th>
        <td>@Model.IsTenured</td>
    </tr>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RomenITELEC1C</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RomenITELEC1C.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RomenITELEC1C</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Instructor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RomenITELEC1C - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Student/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Student List</h1>

<table class="table table-dark">
    <tr>
        <td>Name:</td>
        <td>@ViewBag.StudentModel.StudentName</td>
    </tr>
    <tr>
        <td>Student ID:</td>
        <td>@ViewBag.StudentModel.StudentId</td>
    </tr>
    <tr>
        <td>Date Enrolled:</td>
        <td>@ViewBag.StudentModel.DateEnrolled</td>
    </tr>
    <tr>
        <td>Student Course:</td>
        <td>@ViewBag.StudentModel.StudentCourse</td>
    </tr>
    <tr>
        <td>Email:</td>
        <td>@ViewBag.StudentModel.Email</td>
    </tr>
</table>